# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [5]:
print(A)
print(A.dtype.name)
print(A.shape)
print(A.ndim)
print(A.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
int32
(3, 5)
2
15


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
print(B*C)
print(B-C)
print(B@C)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [8]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np.exp(B))
print(B.min())
print(B.min(axis=1))
print(B.min(axis=0))   
print(np.argmin(B))
print(B.argmin(axis=1))
print(B.sum())
print(B.mean())
print(np.median(B))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
5.0
5.0


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [12]:
#A[1] - means row with the index 1 (i.e.on the second place)
#When fewer indices are provided than the number of axes, the missing indices fills automatically.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [13]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [15]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [16]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [17]:
#a creates an array with 30 elements
#b reshapes the arrays form: 2 matrixs with 3 rows. -1 means that the computer decides automaticallly how long will be a row (we can check and put a 5 instead and it will work. But if we put 4 - it will not work)

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [18]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [19]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [20]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.8, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.15, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [21]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [119]:
def add_mult_matrices (A, B, add_or_multiply):
    if isinstance (A, np.ndarray) and isinstance (B, np.ndarray):
        
        if add_or_multiply == 'add':
            if A.shape == B.shape:
             sum = A + B
             return sum
            else:
              raise Exception ("The matrices must have the same shape")
            
        elif add_or_multiply == 'multiply':
            if not A.shape[1] == B.shape[0]:
                raise ValueError ('The amount of the columns should match with the amount of the rows')
            else: 
             return A@B
        else: 
         raise Exception ('The add_or_multiply must be "add" or "multiply"')
    else: 
     raise Exception ('Please, provide two matrices')


In [120]:
# B - 2A
add_mult_matrices(B, -2*A, 'add')

Exception: The matrices must have the same shape

In [121]:
# 3C - E
add_mult_matrices(3*C, - E, 'add')

Exception: The matrices must have the same shape

In [25]:
# AC
add_mult_matrices(A, C, 'multiply')

ValueError: The amount of the columns should match with the amount of the rows

In [26]:
# CD
add_mult_matrices(C, D, 'multiply')

array([[11, 10],
       [10, 11]])

In [27]:
# CB
add_mult_matrices(C, B, 'multiply')

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

**Chap2. Question 2**

In [28]:
A = np.array ([[1, 2], [2, 4]])
B = np.array ([[2, 1], [1, 3]])
C = np.array ([[4, 3], [0, 2]])

AB = add_mult_matrices(A, B, 'multiply')
AC = add_mult_matrices(A, C, 'multiply')

print(AB)
print()
print(AC)
print('Vi kan se att AB = AC')
print()
print()

print (B)
print()
print(C)
print('Vi kan se att B inte är lika med C')

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]
Vi kan se att AB = AC


[[2 1]
 [1 3]]

[[4 3]
 [0 2]]
Vi kan se att B inte är lika med C


**Chap2. Question 3**

In [29]:
A = np.array ([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array ([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

AD = add_mult_matrices(A, D, 'multiply')
DA = add_mult_matrices(D, A, 'multiply')

print (AD)
print()
print(DA)

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [30]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])

AB = add_mult_matrices(A, B, 'multiply')

print (AB)

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [31]:
A = np.array ([[5, 6], [4, 5]])
B = np.array ([[6, 4], [3, 3]])

print(A)
print()
print(B)

[[5 6]
 [4 5]]

[[6 4]
 [3 3]]


In [36]:
from numpy.linalg import inv
Ainv = inv(A)
print(Ainv)


np.allclose(np.dot(A, Ainv), np.eye(2))
True
np.allclose(np.dot(Ainv, A), np.eye(2))
True

[[ 5. -6.]
 [-4.  5.]]


True

In [80]:
Binv = inv(B)
print(Binv)


np.allclose(np.dot(B, Binv), np.eye(2))

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


True

**Quiz p.19, Question 3**

In [91]:
A = np.array ([[2, 2], [1, 2]])
print (A)

Ainv = inv(A)
print ()
print ('The inverse of the matrix is:')
print(Ainv)


np.allclose(np.dot(Ainv, A), np.eye(2))

[[2 2]
 [1 2]]

The inverse of the matrix is:
[[ 1.  -1. ]
 [-0.5  1. ]]


True

**Chap10. Question 1 a)**

In [92]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([-7, 5, 2])

print(A)
print()
print(b)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

[-7  5  2]


In [93]:
x = np.linalg.solve (A, b)

print(x)

[ 3.  4. -6.]


In [94]:
#Check if solution was correct

np.allclose(np.dot(A, x), b)

True

**Chap10. Question 1 b)**

In [95]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])

print(A)
print()
print(b)

[[ 1 -2  3]
 [-1  3 -1]
 [ 2 -5  5]]

[ 1 -1  1]


In [96]:
x = np.linalg.solve (A, b)
print(x)

[ 8.  2. -1.]


In [97]:
#Check if solution was correct

np.allclose(np.dot(A, x), b)

True

**Chap 12. Question 1**

In [101]:
A = np.array ([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
print (A)

Ainv = np.linalg.inv(A)
print ()
print ('The inverse of the matrix is:')
print(Ainv)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

The inverse of the matrix is:
[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


In [108]:
np.allclose(np.dot(Ainv, A), np.eye(3))

True

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [113]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [117]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [118]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
